name: Publish Release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:

permissions:
  contents: write
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build
        run: |
          dotnet publish 'Community.PowerToys.Run.Plugin.VSCodeWorkspaces.csproj' -c Release -o publish_output
      - name: Prepare package folder
        shell: pwsh
        run: |
          $Version = "${{steps.version.outputs.prop}}"
          $PackageDir = "PowerToys.Run.Plugin.VSCodeWorkspaces"
          if (Test-Path $PackageDir) { Remove-Item $PackageDir -Recurse -Force }
          New-Item -ItemType Directory -Path $PackageDir | Out-Null
          New-Item -ItemType Directory -Path "$PackageDir/Images" | Out-Null
          Copy-Item publish_output/*.dll $PackageDir -Filter 'Community.PowerToys.Run.Plugin.VSCodeWorkspaces.dll'
          Copy-Item publish_output/plugin.json $PackageDir/
          Copy-Item publish_output/*.deps.json $PackageDir -Filter 'Community.PowerToys.Run.Plugin.VSCodeWorkspaces.deps.json'
          Copy-Item publish_output/Images/*.png "$PackageDir/Images/" -ErrorAction SilentlyContinue
          Compress-Archive -Path $PackageDir -DestinationPath "${PackageDir}-$Version.zip"
          Write-Host "Created archive ${PackageDir}-$Version.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "PowerToys.Run.Plugin.VSCodeWorkspaces-*.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
